### ISSUE TITLE
文档欠缺

### ISSUE THREAD

**Issue by jackerzhou** [Joker486/zvue#1]
文档比较欠缺，最为新手，不知道怎么使用哦

**Comment by StrivingRabbit** [comment]
可以访问lxhblog.cn，文档在这里

**Comment by jackerzhou** [comment]
综合用法的代码和基础用法的相关代码，能够共享一下啊，看得不是很明白

**Comment by StrivingRabbit** [comment]
> 综合用法的代码和基础用法的相关代码，能够共享一下啊，看得不是很明白

那些只是单个组件集合起来了，和其他没有什么不一样的地方，就是用来展示可以做成什么样子，具体的详细的使用方法还是在下面的文档中的
